### ISSUE TITLE
Doesn't Compile

### ISSUE THREAD

**Issue by TrinityDevelopers** [MinecraftXenonTeam/xenon-modloader#1]
Pls fix tis code... it don't compile when I go to build it in Xcode... HALP!!
Also is it compatibel with iOS?  I want to ran this launcher in my iPad...
Thanks!

**Comment by byteandahalf** [comment]
Lol Dan get out of here

**Comment by TrinityDevelopers** [comment]
Lol but I'm not Dan... I'm MRAndyPE... :P
